config/routes.rb
Rails.application.routes.draw do
  #コントローラーの指定と余分なルーティングの削除
  devise_for :admins,skip: [:registrations,:passwords], controllers: {
    sessions: "admin/sessions"
  }

  #コントローラーの指定と余分なルーティングの削除
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  root "user/homes#top"

  namespace :admin do
    get 'homes/top'
    resources :shops, only: [:new, :show, :edit, :index, :create, :destroy, :update]
    resources :users, only: [:index, :show, :destroy]
  end

  namespace :user do
    get 'homes/top'
    get "search" => "searches#search"
    resources :users, only: [:show, :edit, :update]
    resources :shops, only: [:show, :index] do
      resource :review
    end
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  has_many :shops, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :shop

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-ramen-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :tags, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :admin
  has_one_attached :image

  def self.looks(search, word)
    if search == "perfect_match"
      @shop = Shop.where("name LIKE?","#{word}")
    elsif search == "forward_match"
      @shop = Shop.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @shop = Shop.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @shop = Shop.where("name LIKE?","%#{word}%")
    else
      @shop = Shop.all
    end
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-ramen-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :shop
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_one_attached :profile_image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #user情報編集時バリデーションが適用されない
  validates :password, presence: true, on: :create

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    @shop.admin_id = current_admin.id
    tags = Vision.get_image_data(shop_params[:image])
    if @shop.save
      tags.each do |tag|
        @shop.tags.create(name: tag)
      end
      redirect_to admin_shops_path
    else
      render :new
    end
  end

  def show
    @shop = Shop.find(params[:id])
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def update
    @shop = Shop.find(params[:id])
    # 既存のタグを削除
    @shop.tags.destroy_all
        # タグを新しく検出
    tags = Vision.get_image_data(shop_params[:image])
    if @shop.update(shop_params)
      # 新しいタグを作成
      tags.each do |tag|
        @shop.tags.create(name: tag)
      end
      redirect_to admin_shop_path(@shop.id)
    else
      render :edit
    end
  end

  def index
    @shops = Shop.all
  end

  private

  def shop_params
    params.require(:shop).permit(:admin_id, :name, :address, :phone, :first_hour, :first_min, :end_hour, :end_min, :closed, :access, :parking, :remarks, :image)
  end


end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end


  def destroy
    review = Review.find(params[:id])
    review.destroy
    redirect_to admin_users_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/user/reviews_controller.rb
class User::ReviewsController < ApplicationController

  def create
    shop = Shop.find(params[:shop_id])
    review = current_user.reviews.new(review_params)
    review.shop_id = shop.id
    review.save
    redirect_to user_shop_path(shop)
  end

  private

    def review_params
      params.require(:review).permit(:shop_id, :user_id, :title, :content, :star)
    end

end

app/controllers/user/shops_controller.rb
class User::ShopsController < ApplicationController
  def index
    @shops = Shop.all
  end

  def show
    @shop = Shop.find(params[:id])
    @review = @shop.reviews
  end

  def create
    @shop = Shop.find(params[:id])
    @review = @shop.reviews.build(review_params)
    @review.user_id = current_user.id
    if @review.save
      @shop = Shop.find(params[:id])
      redirect_to user_shops_path
    else
      render :show
    end
  end

  private

    def review_params
      params.require(:review).permit(:shop_id, :user_id, :title, :content, :star)
    end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_user_path(current_user)
    else
      redirect_to request.referer
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :email)
  end

end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/reviews_helper.rb
module User::ReviewsHelper
end

app/helpers/user/shops_helper.rb
module User::ShopsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/admin/shops/edit.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-2">
      <h1>店舗情報編集</h1>
      <%= form_with model: @shop, url: admin_shop_path, local:true do |f| %>
        <h4>店名</h4>
        <%= f.text_field :name %>
        <h4>住所</h4>
        <%= f.text_area :address %>
        <h4>電話番号</h4>
        <%= f.text_field :phone %>
        <h4>営業時間</h4>
        <%= f.select :first_hour,  *[0..28], :prompt => "開店時刻(hour)" %>:<%= f.select :first_min,  *[0..59], :prompt => "開店時刻(min)" %>~<%= f.select :end_hour,  *[0..28], :prompt => "閉店時刻(hour)" %>:<%= f.select :end_min,  *[0..59], :prompt => "閉店時刻(min)" %>
        <h4>休業日</h4>
        <%= f.text_field :closed %>
        <h4>アクセス</h4>
        <%= f.text_area :access %>
        <h4>駐車場</h4>
        <%= f.radio_button :parking, "false" %>なし
        <%= f.radio_button :parking, "true" %>あり
        <h4>備考</h4>
        <%= f.text_area :remarks %>
        <h4>画像</h4>
        <%= f.file_field :image %>
        <%= f.submit '編集を保存' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/shops/index.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-2">
      <%= link_to "新規投稿", new_admin_shop_path %>
      <% @shops.each do |shop| %>
        <table>
          <tbody>
            <tr>
              <td>
                <%= link_to admin_shop_path(shop) do %>
                  <%= image_tag shop.get_image(100, 100) %>
                <% end %>
              </td>
              <td>
                <%= shop.id %>
              </td>
              <td>
                <%= link_to admin_shop_path(shop) do %>
                  <%= shop.name %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/shops/new.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-2">
      <h1>新規投稿</h1>
      <%= form_with model: @shop, url: admin_shops_path, local:true do |f| %>
        <h4>店名</h4>
        <%= f.text_field :name %>
        <h4>住所</h4>
        <%= f.text_area :address %>
        <h4>電話番号</h4>
        <%= f.text_field :phone %>
        <h4>営業時間</h4>
        <%= f.select :first_hour,  *[0..28], :prompt => "開店時刻(hour)" %>:<%= f.select :first_min,  *[0..59], :prompt => "開店時刻(min)" %>~<%= f.select :end_hour,  *[0..28], :prompt => "閉店時刻(hour)" %>:<%= f.select :end_min,  *[0..59], :prompt => "閉店時刻(min)" %>
        <h4>休業日</h4>
        <%= f.text_field :closed %>
        <h4>アクセス</h4>
        <%= f.text_area :access %>
        <h4>駐車場</h4>
        <%= f.radio_button :parking, "false" %>なし
        <%= f.radio_button :parking, "true" %>あり
        <h4>備考</h4>
        <%= f.text_area :remarks %>
        <h4>画像</h4>
        <%= f.file_field :image %>
        <%= f.submit '投稿' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/shops/show.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-2">
      <h1><%= @shop.name %>の店舗詳細</h1>
      <h4>店名</h4>
      <%= @shop.name %>
      <h4>住所</h4>
      <%= @shop.address %>
      <h4>電話番号</h4>
      <%= @shop.phone %>
      <h4>営業時間</h4>
      <%= @shop.first_hour %>:<%= @shop.first_min %>~<%= @shop.end_hour %>:<%= @shop.end_min %>
      <h4>休業日</h4>
      <%= @shop.closed %>
      <h4>アクセス</h4>
      <%= @shop.access %>
      <h4>駐車場</h4>
      <% if @shop.parking == "true" %>
        <p>あり</p>
      <% else %>
        <p>なし</p>
      <% end %>
      <h4>備考</h4>
      <%= @shop.remarks %>
      <h4>画像</h4>
      <%= image_tag @shop.get_image(100, 100) %>
      <div class="tag-box">
        <% @shop.tags.each do |tag| %>
        <span class="label"><%= tag.name %></span>
        <% end %>
      </div>
      <%= link_to "編集", edit_admin_shop_path %>
    </div>
  </div>
</div>